# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [87]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [88]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [89]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [90]:
a=np.zeros(16).reshape(4,4)
print(a.itemsize)
a.size

8


16

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [91]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [92]:
array=np.zeros(10)
array[4]=1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [93]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [94]:
n=np.arange(10,40)
n[::-1]

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [95]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [96]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [97]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [98]:
# np.random.randint(0,9,(3,3,3))
np.random.random(27).reshape(3,3,3)

array([[[0.3864, 0.9226, 0.907 ],
        [0.9552, 0.9288, 0.8279],
        [0.454 , 0.1535, 0.1932]],

       [[0.0968, 0.5333, 0.8387],
        [0.6331, 0.1336, 0.8736],
        [0.5885, 0.9624, 0.4779]],

       [[0.4206, 0.262 , 0.5995],
        [0.9663, 0.338 , 0.694 ],
        [0.293 , 0.0792, 0.9574]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [99]:
a=np.random.randint(1,100,(10,10))
print(a.max())
print(a.min())

99
2


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [100]:
np.random.random(30).mean()

0.48371365254258675

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [101]:
ar=np.zeros(9).reshape(3,3)
ar+=1
ar[1:-1,1:-1]=0
ar

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [102]:
np.pad([1,2,3,4,5],(3,2))

array([0, 0, 0, 1, 2, 3, 4, 5, 0, 0])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [103]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [104]:
n=np.arange(4)
m=np.diag(1+n,k=-1)
m

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [105]:
n=np.zeros(64).reshape(8,8)
n[1::2,::2] = 1
n[::2,1::2] = 1
n

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [106]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [107]:
ar=np.array([[0,1],[1,0]])
np.tile(ar,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [108]:
# check later
ar=np.arange(1,26).reshape(5,5)
ar=(ar-ar.min())/(ar.max()-ar.min())
ar

array([[0.    , 0.0417, 0.0833, 0.125 , 0.1667],
       [0.2083, 0.25  , 0.2917, 0.3333, 0.375 ],
       [0.4167, 0.4583, 0.5   , 0.5417, 0.5833],
       [0.625 , 0.6667, 0.7083, 0.75  , 0.7917],
       [0.8333, 0.875 , 0.9167, 0.9583, 1.    ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [109]:
custom_color = np.dtype([("r", np.ubyte),
                          ("g", np.ubyte),
                          ("b", np.ubyte),
                          ("a", np.ubyte)
                        ])
custom_color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [110]:
m1=np.arange(1,16).reshape(5,3)
m2=np.arange(5,11).reshape(3,2)
np.dot(m1,m2)

array([[ 46,  52],
       [109, 124],
       [172, 196],
       [235, 268],
       [298, 340]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [111]:
arr=np.arange(0,15)
arr[(arr>3) & (arr<9)]*=-1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [112]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [113]:
Z=np.random.randint(0,10)
print(Z**Z)   
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

1
1
False
1j
1.0
False


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [114]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.2234e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [115]:
n = np.array([-3.55,14.32,-10.14,4.8,-14.5])
print(n)
n1=np.random.uniform(n)
print(n1)
n2=np.abs(n)
print(n2)
n3=np.floor(n)
print(n3)
n4=np.ceil(n)
print(n4)
n5=np.copysign(n,n4)
print(n5)

[ -3.55  14.32 -10.14   4.8  -14.5 ]
[ -2.6294  13.0392  -4.6219   2.3485 -11.8922]
[ 3.55 14.32 10.14  4.8  14.5 ]
[ -4.  14. -11.   4. -15.]
[ -3.  15. -10.   5. -14.]
[ -3.55  14.32 -10.14   4.8  -14.5 ]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [116]:
m1=np.arange(0,10)
m2=np.arange(5,15)
np.intersect1d(m1,m2)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [117]:
np.errstate(divide='warn')
np.seterr(all='ignore')

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [118]:
# NO
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [119]:
import datetime
yest_date=datetime.datetime.today()-datetime.timedelta(1)
curr_date=datetime.datetime.today()
tomr_date=datetime.datetime.today()+datetime.timedelta(1)

print("Yesterday: ",yest_date)
print("Today: ",curr_date)
print("Tomorrow: ",tomr_date)


Yesterday:  2022-07-18 07:10:49.801000
Today:  2022-07-19 07:10:49.801048
Tomorrow:  2022-07-20 07:10:49.801087


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [120]:
(np.arange('2016-07','2016-08', dtype='datetime64[D]'))

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [121]:
A=np.arange(1,6)
B=np.arange(6,11)
# m=(A+B)*(-A/2)

B=np.add(A,B)
A=np.negative(A)
A=np.divide(A,2)
B=np.multiply(A,B)
B

array([ -3.5,  -9. , -16.5, -26. , -37.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [122]:
a=np.array([6.78])
print(a-a%1) 
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(a.astype(int))

[6.]
[6.]
[7.]
[6.]
[6]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [123]:
a=np.zeros((5,5))
a+=np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [124]:
np.fromiter(np.arange(10),dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [125]:
n=np.linspace(0,1,11,endpoint=False)[1:]
n

array([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273,
       0.8182, 0.9091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [126]:
a=np.random.random(10)
print(a)
np.sort(a)

[0.1369 0.5995 0.928  0.1225 0.5155 0.4414 0.1282 0.5335 0.6176 0.8899]


array([0.1225, 0.1282, 0.1369, 0.4414, 0.5155, 0.5335, 0.5995, 0.6176,
       0.8899, 0.928 ])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [127]:
a=np.arange(10)
print(a)
np.add.reduce(a)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [128]:
m1=np.random.random(10)
m2=np.random.random(10)
print(np.array_equal(m1,m2))
print(np.allclose(m1,m2))

n1=np.arange(0,10)
n2=np.arange(0,10)
print(np.array_equal(n1,n2))
print(np.allclose(n1,n2))

False
False
True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [129]:
ar=np.arange(10)
ar.flags.writeable=False
# ar[1]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [130]:
n = np.random.random((10,2))
print(n)
x,y = n[:,0], n[:,1]
a = np.sqrt(x**2+x**2)
p_coord = np.arctan2(y,x)
print(p_coord)

[[0.1501 0.1441]
 [0.7189 0.7913]
 [0.3821 0.5523]
 [0.5289 0.953 ]
 [0.8525 0.9171]
 [0.1559 0.6164]
 [0.9578 0.1971]
 [0.7581 0.2548]
 [0.2828 0.0126]
 [0.6758 0.224 ]]
[0.7651 0.8333 0.9656 1.0641 0.8219 1.3231 0.203  0.3243 0.0445 0.3201]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [131]:
n=np.arange(10)
n[np.argmax(n)]=0
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [132]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
Z

array([[(0.    , 0.    ), (0.1111, 0.    ), (0.2222, 0.    ),
        (0.3333, 0.    ), (0.4444, 0.    ), (0.5556, 0.    ),
        (0.6667, 0.    ), (0.7778, 0.    ), (0.8889, 0.    ),
        (1.    , 0.    )],
       [(0.    , 0.1111), (0.1111, 0.1111), (0.2222, 0.1111),
        (0.3333, 0.1111), (0.4444, 0.1111), (0.5556, 0.1111),
        (0.6667, 0.1111), (0.7778, 0.1111), (0.8889, 0.1111),
        (1.    , 0.1111)],
       [(0.    , 0.2222), (0.1111, 0.2222), (0.2222, 0.2222),
        (0.3333, 0.2222), (0.4444, 0.2222), (0.5556, 0.2222),
        (0.6667, 0.2222), (0.7778, 0.2222), (0.8889, 0.2222),
        (1.    , 0.2222)],
       [(0.    , 0.3333), (0.1111, 0.3333), (0.2222, 0.3333),
        (0.3333, 0.3333), (0.4444, 0.3333), (0.5556, 0.3333),
        (0.6667, 0.3333), (0.7778, 0.3333), (0.8889, 0.3333),
        (1.    , 0.3333)],
       [(0.    , 0.4444), (0.1111, 0.4444), (0.2222, 0.4444),
        (0.3333, 0.4444), (0.4444, 0.4444), (0.5556, 0.4444),
        (0.6667, 0.4444)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [133]:
x=np.arange(1,5)
y=np.arange(5,10)
1/np.subtract.outer(x,y)

array([[-0.25  , -0.2   , -0.1667, -0.1429, -0.125 ],
       [-0.3333, -0.25  , -0.2   , -0.1667, -0.1429],
       [-0.5   , -0.3333, -0.25  , -0.2   , -0.1667],
       [-1.    , -0.5   , -0.3333, -0.25  , -0.2   ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [134]:
# Range of all datatypes
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [135]:
# its written so as not to get the scientific notations in the numeric values
n=np.array([1.232434,3.34434324,4,3434343,34.4343])
np.set_printoptions(precision=4,suppress=True)
print(n)

[      1.2324       3.3443       4.     3434343.          34.4343]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [136]:
n = np.arange(100)
m = np.random.uniform(0,100)
ind = (np.abs(n-m)).argmin()
print(n[ind])

19


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [137]:
n=np.zeros(10,[('position', [('x', float, 1),
                            ('y', float, 1)]),
                  ('color', [('r', float, 1),
                            ('g', float, 1),
                            ('b', float, 1)])])
n

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [138]:
n=np.random.random((10,2))
x,y=np.atleast_2d(n[:,0]), np.atleast_2d(n[:,1])
dist=np.sqrt((x-x.T)**2+(y-y.T)**2)
dist

array([[0.    , 0.3118, 0.1466, 0.3548, 0.6205, 0.8745, 0.1371, 1.0639,
        0.7987, 0.0703],
       [0.3118, 0.    , 0.4208, 0.4044, 0.725 , 0.6095, 0.1824, 0.8968,
        0.5449, 0.3268],
       [0.1466, 0.4208, 0.    , 0.4924, 0.7299, 1.0098, 0.2699, 1.2106,
        0.9363, 0.0963],
       [0.3548, 0.4044, 0.4924, 0.    , 0.3206, 0.6923, 0.3097, 0.7545,
        0.6082, 0.4243],
       [0.6205, 0.725 , 0.7299, 0.3206, 0.    , 0.8876, 0.6164, 0.7771,
        0.8074, 0.6893],
       [0.8745, 0.6095, 1.0098, 0.6923, 0.8876, 0.    , 0.7407, 0.4476,
        0.0842, 0.9137],
       [0.1371, 0.1824, 0.2699, 0.3097, 0.6164, 0.7407, 0.    , 0.9559,
        0.6664, 0.1746],
       [1.0639, 0.8968, 1.2106, 0.7545, 0.7771, 0.4476, 0.9559, 0.    ,
        0.4377, 1.1231],
       [0.7987, 0.5449, 0.9363, 0.6082, 0.8074, 0.0842, 0.6664, 0.4377,
        0.    , 0.8405],
       [0.0703, 0.3268, 0.0963, 0.4243, 0.6893, 0.9137, 0.1746, 1.1231,
        0.8405, 0.    ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [139]:
a=np.array([1,2,3,4,5],dtype=float)
print(a)
a=a.astype(np.int32,copy=False)
a

[1. 2. 3. 4. 5.]


array([1, 2, 3, 4, 5], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [141]:
np.genfromtxt('text.csv',delimiter=',',missing_values=None)

OSError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [142]:
n=np.array([1,2,3,4,5,6,7])

for ind,x in np.ndenumerate(n):
  print(ind,x)
print("\n")
for a in np.ndindex(n.shape):
    print(a,n[a])

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7


(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [143]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
D

array([[1.4142, 1.2669, 1.144 , 1.0541, 1.0062, 1.0062, 1.0541, 1.144 ,
        1.2669, 1.4142],
       [1.2669, 1.0999, 0.9558, 0.8462, 0.7857, 0.7857, 0.8462, 0.9558,
        1.0999, 1.2669],
       [1.144 , 0.9558, 0.7857, 0.6479, 0.5666, 0.5666, 0.6479, 0.7857,
        0.9558, 1.144 ],
       [1.0541, 0.8462, 0.6479, 0.4714, 0.3514, 0.3514, 0.4714, 0.6479,
        0.8462, 1.0541],
       [1.0062, 0.7857, 0.5666, 0.3514, 0.1571, 0.1571, 0.3514, 0.5666,
        0.7857, 1.0062],
       [1.0062, 0.7857, 0.5666, 0.3514, 0.1571, 0.1571, 0.3514, 0.5666,
        0.7857, 1.0062],
       [1.0541, 0.8462, 0.6479, 0.4714, 0.3514, 0.3514, 0.4714, 0.6479,
        0.8462, 1.0541],
       [1.144 , 0.9558, 0.7857, 0.6479, 0.5666, 0.5666, 0.6479, 0.7857,
        0.9558, 1.144 ],
       [1.2669, 1.0999, 0.9558, 0.8462, 0.7857, 0.7857, 0.8462, 0.9558,
        1.0999, 1.2669],
       [1.4142, 1.2669, 1.144 , 1.0541, 1.0062, 1.0062, 1.0541, 1.144 ,
        1.2669, 1.4142]])

In [144]:
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / ( 2.0 * sigma**2 )))
print(G)

[[0.3679 0.4482 0.5198 0.5738 0.6028 0.6028 0.5738 0.5198 0.4482 0.3679]
 [0.4482 0.5461 0.6333 0.6991 0.7344 0.7344 0.6991 0.6333 0.5461 0.4482]
 [0.5198 0.6333 0.7344 0.8107 0.8517 0.8517 0.8107 0.7344 0.6333 0.5198]
 [0.5738 0.6991 0.8107 0.8948 0.9401 0.9401 0.8948 0.8107 0.6991 0.5738]
 [0.6028 0.7344 0.8517 0.9401 0.9877 0.9877 0.9401 0.8517 0.7344 0.6028]
 [0.6028 0.7344 0.8517 0.9401 0.9877 0.9877 0.9401 0.8517 0.7344 0.6028]
 [0.5738 0.6991 0.8107 0.8948 0.9401 0.9401 0.8948 0.8107 0.6991 0.5738]
 [0.5198 0.6333 0.7344 0.8107 0.8517 0.8517 0.8107 0.7344 0.6333 0.5198]
 [0.4482 0.5461 0.6333 0.6991 0.7344 0.7344 0.6991 0.6333 0.5461 0.4482]
 [0.3679 0.4482 0.5198 0.5738 0.6028 0.6028 0.5738 0.5198 0.4482 0.3679]]




#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [145]:
n=5
p=3
m=np.zeros((n,n))
np.put(m, np.random.choice(range(n*n), p, replace=False),1)
print(m)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [146]:
n=np.arange(21).reshape(3,7)
print(n)
m=n-n.mean(axis=1,keepdims=True)
m

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


array([[-3., -2., -1.,  0.,  1.,  2.,  3.],
       [-3., -2., -1.,  0.,  1.,  2.,  3.],
       [-3., -2., -1.,  0.,  1.,  2.,  3.]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [147]:
n=np.array([20,14,30,66,7,9,12,11,3,52,2,4,8,10,13,70]).reshape(4,4)
print(n)
print(n[n[:,1].argsort()])

[[20 14 30 66]
 [ 7  9 12 11]
 [ 3 52  2  4]
 [ 8 10 13 70]]
[[ 7  9 12 11]
 [ 8 10 13 70]
 [20 14 30 66]
 [ 3 52  2  4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [148]:
n=np.arange(16).reshape(4,4)
print((~n.any(axis=0)).any())


False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [149]:
n=np.random.uniform(0,1,10)
print(n)
x=0.5
m=n.flat[np.abs(n - x).argmin()]
print(m)

[0.0948 0.8104 0.2493 0.9129 0.9646 0.0157 0.7723 0.1017 0.789  0.6437]
0.6437380494213936


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [150]:
n=np.arange(3).reshape(1,3)
m=np.arange(3).reshape(3,1)
s=0
for x in np.nditer(n):
  s+=x
for x in np.nditer(m):
  s+=x
s

6

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [151]:
# class array_class(np.ndarray):
#     def __init__(self,name):
#       self.name=name
                       
    
#     def __new__(cls, array, name="no name"):
#         obj = np.asarray(array).view(cls)
#         obj.name = name
#         return obj
#     def __array_finalize__(self, obj):
#         if obj is None: return
#         self.info = getattr(obj, 'name', "no name")

# Z = NamedArray(np.arange(10), "range_10")
# print (Z.name)
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)



check 63 again.

SyntaxError: ignored

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [152]:
n=np.zeros(10)
m=np.random.randint(0,len(n),20)
print(n)
n+=np.bincount(m, minlength=len(n))
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 3. 2. 3. 2. 3. 0. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [153]:
X=[1,2,3,4,5,6]
I=[1,3,9,3,4,1]
F=np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [154]:
w,h = 16,16
n = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
m = n[...,0]*256*256 + n[...,1]*256 +n[...,2]
new_n = len(np.unique(m))
np.unique(new_n)

array([4])

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [155]:
n=np.zeros(256).reshape(4,4,4,4)
n+=1
print(n.sum(axis=(-2,-1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [156]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
D_means

array([0.6219, 0.3612, 0.5432, 0.4508, 0.6225, 0.5603, 0.5182, 0.343 ,
       0.462 , 0.3783])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [157]:
m1=np.random.randint(0,5,(5,5))
m2=np.random.randint(0,5,(5,5))
np.diag(np.dot(m1,m2))

array([32,  2, 16, 14, 12])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [158]:
n=np.array([1,2,3,4,5])
m=np.zeros(3)
l=np.empty(10)
k=np.empty(10)
count=0
for i in n:
  count+=1
  if count==n.size:break
  l=np.append(i,m)
  k=np.append(k,l)
  # print('l',l)
k=np.append(k,n[-1])
l=k[10:]
l


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [159]:
n=np.ones((5,5,3))
m=2*np.ones((5,5))
n*m[:,:,None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [160]:
n=np.random.randint(0,19,(2,10))
print(n)
n[[0,1]]=n[[1,0]]
n

[[14 16  9  7 14  0  5  5 12  3]
 [ 7  6  3  0  3 15 18  8  3 10]]


array([[ 7,  6,  3,  0,  3, 15, 18,  8,  3, 10],
       [14, 16,  9,  7, 14,  0,  5,  5, 12,  3]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [4]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.49473635  5.28258765 10.13737345  3.90581788  3.90302675 13.44830693
 10.02256983  0.49410257 11.05232255  5.21550044]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [5]:
n=np.bincount([1,1,2,3,4,4,6])
m=np.repeat(np.arange(len(n)),n)
m

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [6]:
# for 1D Array
n=np.arange(10)
print(n)
print(np.cumsum(n))
# for 2D Array
n=np.arange(6).reshape(2,3)
print(n)
print(np.cumsum(n,axis=0))
print(np.cumsum(n,axis=1))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 5 7]]
[[ 0  1  3]
 [ 3  7 12]]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [7]:
import numpy as np
from numpy.lib import stride_tricks
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
G

array([( 1, 10), ( 1, 20), ( 2, 24), ( 2, 33), ( 2, 37), ( 2, 78),
       ( 6, 75), ( 6, 95), ( 8, 20), ( 8, 46), ( 9, 28), ( 9, 55),
       (10, 20), (11, 38), (11, 87), (13, 56), (13, 91), (20, 46),
       (24, 37), (28, 55), (29, 93), (29, 96), (33, 78), (38, 87),
       (55, 84), (55, 96), (56, 91), (75, 95), (84, 96), (93, 96)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [45]:
n=np.arange(10,dtype=float)
n*=-1       #one method is simply mutliplication by -1
print(np.negative(n))
print(np.logical_not(n))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ True False False False False False False False False False]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [46]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.04465899  5.06857036  3.65195592 14.61770315 12.3062699   5.53010898
  4.38785922  4.20942625  8.80334143 10.82483569]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [47]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.73907758  1.11853779  9.57766138  0.2721796   8.32397234]
 [12.26541594  5.70636422 16.58589968  8.88810857  1.34288204]
 [ 3.94653846  3.52410683  7.23892078  1.25936011  8.17052439]
 [ 2.28685764  6.60784856  3.94203622  6.64456319 16.06809094]
 [ 3.87043782  2.68609086  8.21689039  1.1434834   3.8022499 ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [11]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
R

[[4 7 8 3 4 6 1 9 9 1]
 [9 1 7 3 9 6 4 6 4 4]
 [9 4 1 9 6 3 7 4 5 4]
 [7 9 4 6 7 8 9 0 6 6]
 [8 2 9 9 7 4 4 8 8 2]
 [8 4 4 3 6 0 9 7 1 6]
 [0 5 9 2 6 1 9 8 6 7]
 [4 1 2 7 8 2 0 4 2 9]
 [5 0 7 6 7 8 7 4 2 5]
 [2 8 0 2 4 8 0 4 6 6]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


array([[0, 0, 0, 0, 0],
       [0, 4, 7, 8, 3],
       [0, 9, 1, 7, 3],
       [0, 9, 4, 1, 9],
       [0, 7, 9, 4, 6]])

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [12]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
R

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 


array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [13]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
rank

10

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [14]:
n=np.array([1,2,3,3,3,3,3,3,5,6,7,7,7,7,8])
np.argmax(np.bincount(n))

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [15]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[2, 1, 1],
         [1, 1, 3],
         [0, 2, 4]],

        [[1, 1, 2],
         [1, 3, 4],
         [2, 4, 4]],

        [[1, 2, 4],
         [3, 4, 0],
         [4, 4, 2]],

        [[2, 4, 3],
         [4, 0, 0],
         [4, 2, 2]],

        [[4, 3, 4],
         [0, 0, 3],
         [2, 2, 3]],

        [[3, 4, 3],
         [0, 3, 4],
         [2, 3, 2]],

        [[4, 3, 2],
         [3, 4, 3],
         [3, 2, 2]],

        [[3, 2, 3],
         [4, 3, 2],
         [2, 2, 4]]],


       [[[1, 1, 3],
         [0, 2, 4],
         [4, 2, 2]],

        [[1, 3, 4],
         [2, 4, 4],
         [2, 2, 0]],

        [[3, 4, 0],
         [4, 4, 2],
         [2, 0, 3]],

        [[4, 0, 0],
         [4, 2, 2],
         [0, 3, 3]],

        [[0, 0, 3],
         [2, 2, 3],
         [3, 3, 1]],

        [[0, 3, 4],
         [2, 3, 2],
         [3, 1, 2]],

        [[3, 4, 3],
         [3, 2, 2],
         [1, 2, 4]],

        [[4, 3, 2],
         [2, 2, 4],
         [2, 4, 3]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [21]:
p, n = 10, 20
m=np.ones((p,n,n))
k=np.ones((p,n,1))
l=np.tensordot(m, k, axes=[[0, 2], [0, 1]])
print(l)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [22]:
n=np.ones((16,16))
k=4
block=np.add.reduceat(np.add.reduceat(n, np.arange(0, n.shape[0], k), axis=0),
                                       np.arange(0, n.shape[1], k), axis=1)
print(n)
block

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [24]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
Z

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [25]:
n=np.arange(100)
np.random.shuffle(Z)
x=5
print(n[np.argsort(n)[-x:]])
print(n[np.argpartition(-n,x)[:x]])

[95 96 97 98 99]
[98 99 97 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [26]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [27]:
n=np.array([(1,2,3),(11,12,13)])
np.core.records.fromarrays(n.T, names='col1, col2, col3', formats = 'S8, f8, i8')

rec.array([(b'1',  2.,  3), (b'11', 12., 13)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [58]:
x = np.random.rand(5,7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

The slowest run took 12.78 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 4.33 µs per loop
The slowest run took 13.48 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.05 µs per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [50]:
A=np.random.randint(0,7,(8,3))
B=np.random.randint(0,7,(2,2))
C=(A[..., np.newaxis, np.newaxis] == B)
np.where(C.any((3,1)).all(1))[0]

array([1, 3, 5])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [51]:
n=np.random.randint(0,19,(10,3))
m=np.logical_and.reduce(n[:,1:] == n[:,:-1], axis=1)
n_new=n[~m]
print(n)
print(n_new)

[[ 2  6  0]
 [16  8 14]
 [18  9  2]
 [ 4 13  5]
 [ 2  0  1]
 [ 7 10  7]
 [ 6  2 14]
 [13 10  4]
 [14 18  2]
 [15  2 14]]
[[ 2  6  0]
 [16  8 14]
 [18  9  2]
 [ 4 13  5]
 [ 2  0  1]
 [ 7 10  7]
 [ 6  2 14]
 [13 10  4]
 [14 18  2]
 [15  2 14]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [52]:
n=np.ndarray([0, 1,2,34,5,6,7,9], dtype=np.uint8)
np.unpackbits(n)
n

array([], shape=(0, 1, 2, 34, 5, 6, 7, 9), dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [53]:
n=np.array(([1 ,1, 2],
              [2 ,1, 1],
              [2 ,1, 1],
              [1 ,0, 1],
              [1 ,1, 2]
            ))
print(n)
# np.ascontiguousarray(n)     #ascontiguous gives contiguous array rows not unique, so used unique instead.
np.unique(n,axis=0)


[[1 1 2]
 [2 1 1]
 [2 1 1]
 [1 0 1]
 [1 1 2]]


array([[1, 0, 1],
       [1, 1, 2],
       [2, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [54]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A) # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B) # np.inner(A, B)
np.einsum('i,j', A, B) # np.outer(A, B)

array([[0.22819776, 0.0884009 , 0.12573711, 0.05054167, 0.03151755,
        0.21321245, 0.22278775, 0.04227126, 0.05825434, 0.18715256],
       [0.41233017, 0.15973145, 0.22719419, 0.09132366, 0.05694902,
        0.38525324, 0.40255484, 0.07637988, 0.10525968, 0.33816566],
       [0.16513946, 0.06397292, 0.09099195, 0.0365754 , 0.02280825,
        0.15429507, 0.16122441, 0.03059037, 0.04215681, 0.13543636],
       [0.19803231, 0.07671519, 0.10911593, 0.04386057, 0.02735125,
        0.18502791, 0.19333745, 0.03668343, 0.0505537 , 0.16241287],
       [0.16565523, 0.06417273, 0.09127614, 0.03668963, 0.02287949,
        0.15477697, 0.16172795, 0.03068591, 0.04228848, 0.13585936],
       [0.08199372, 0.03176332, 0.04517859, 0.01816012, 0.01132457,
        0.07660935, 0.08004985, 0.01518848, 0.02093136, 0.06724577],
       [0.41913817, 0.16236878, 0.2309454 , 0.09283151, 0.05788931,
        0.39161417, 0.40920143, 0.07764099, 0.10699762, 0.34374912],
       [0.2689081 , 0.10417157, 0.1481685

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [55]:
X=np.random.randint(0,5,(10,2))
Y=np.random.randint(0,5,(10,2))
print(X)
# UNDEF = -99.0
# np.interp(2.5,X,Y,right=UNDEF)
np.cumsum((X,Y))

[[1 1]
 [1 4]
 [1 0]
 [3 2]
 [4 2]
 [2 2]
 [2 1]
 [2 2]
 [3 0]
 [1 1]]


array([ 1,  2,  3,  7,  8,  8, 11, 13, 17, 19, 21, 23, 25, 26, 28, 30, 33,
       33, 34, 35, 39, 43, 47, 50, 54, 55, 59, 59, 59, 60, 61, 65, 67, 69,
       71, 74, 76, 76, 80, 80])

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [56]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
X[M]

array([[2., 0., 1., 1.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [57]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
confint

array([-0.28147747,  0.09833062])